environment:
  vers: "2.1.1"

version: '{branch}/2.1.1.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
for:
# for master branch
-
  branches:
    only:
      - master

  environment:
    type: release

  artifacts:
  - path: $(platform)\$(CONFIGURATION)\Display-Lock.exe
    name: master/

# for develop branch
-
  branches:
    only:
      - develop

  environment:
    type: develop

  artifacts:
  - path: $(platform)\$(CONFIGURATION)\Display-Lock.exe
    name: develop/

before_build:
  - cmd: python %APPVEYOR_BUILD_FOLDER%\scripts\buildInc.py %TYPE% %vers% %APPVEYOR_BUILD_NUMBER%

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
- cmd: >-
    vstest.console /logger:Appveyor %platform%\%CONFIGURATION%\tests.dll

deploy:
  release: $(APPVEYOR_REPO_TAG)
  description: 'CHANGELOG.md'
  provider: GitHub
  auth_token:
    secure: vbPb3hILx+iWo3VB+iv9e31ERIu15MweDa+3VOIvwr3wqdeeu+O5NWB5Dqawug6i # your encrypted token from GitHub
  artifact: $(platform)\$(CONFIGURATION)\Display-Lock.exe            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
