version: '{branch}/2.0.0{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

before_build:
  - cmd: python %APPVEYOR_BUILD_FOLDER%\scripts\buildInc.py %CONFIGURATION% %version% %APPVEYOR_BUILD_NUMBER%

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
- cmd: >-
    vstest.console /logger:Appveyor %platform%\%CONFIGURATION%\tests.dll