version: '{branch}/2.0.0{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
for:
#
-
  branches:
    only:
      - master
  
  environment:
    type: release

# for develop branch
-
  branches:
    only:
      - develop

  environment:
    type: develop


before_build:
  - cmd: python %APPVEYOR_BUILD_FOLDER%\scripts\buildInc.py %TYPE% %version% %APPVEYOR_BUILD_NUMBER%

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
- cmd: >-
    vstest.console /logger:Appveyor %platform%\%CONFIGURATION%\tests.dll