environment:
  vers: "2.1.0"

version: '{branch}/2.1.0.{build}'

branches:
  only:
    - master
    - develop

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
for:
# for master branch
-
  branches:
    only:
      - master

  environment:
    type: release

  artifacts:
  - path: $(platform)\$(CONFIGURATION)\Display-Lock.exe
    name: master/

# for develop branch
-
  branches:
    only:
      - develop

  environment:
    type: develop

  artifacts:
  - path: $(platform)\$(CONFIGURATION)\Display-Lock.exe
    name: develop/

before_build:
  - cmd: python %APPVEYOR_BUILD_FOLDER%\scripts\buildInc.py %TYPE% %vers% %APPVEYOR_BUILD_NUMBER%

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
- cmd: >-
    vstest.console /logger:Appveyor %platform%\%CONFIGURATION%\tests.dll
