version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
- cmd: >-
    vstest.console /logger:Appveyor $(PLATFORM)\$(CONFIGURATION)\unittest1.dll