version: '{branch}2.0.0{build}'

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
- cmd: >-
    vstest.console /logger:Appveyor $(APPVEYOR_BUILD_FOLDER)\$(configuration)